export const diceInsults: string[] = [
  "You call that a roll? My grandma rolls better. She's dead.",
  "I've seen better numbers on a broken calculator.",
  "You're the reason I have trust issues.",
  "Even loaded dice would be embarrassed by you.",
  "You absolute cube of disappointment.",
  "My expectations were low but HOLY CRAP.",
  "Did you learn to roll from a tutorial on how to SUCK?",
  "You're not even a die. You're a don't.",
  "I've seen better randomness from a rock.",
  "You're the participation trophy of dice.",
  "Did your mother drop you? Multiple times? ON EVERY FACE?",
  "You peaked when you were manufactured.",
  "You make snake eyes look like a jackpot.",
  "I bet you think 1 is your personality score too.",
  "You're why mathematicians drink.",
  "Congratulations on being consistently worthless.",
  "Even the corner of a room has more sides than your talent.",
  "You're the 'new Coke' of dice.",
  "I've seen better odds in a dumpster fire.",
  "Your probability distribution is a war crime.",
  "You make RNG look rigged.",
  "Did Satan personally craft you from pure spite?",
  "You're so bad, casinos would PAY you to leave.",
  "I regret every roll I've ever given you.",
  "You're living proof that cubes can be failures.",
  "Your mother was a paperweight and your father was a pebble.",
  "I've seen more luck in a funeral home raffle.",
  "You couldn't roll a 6 if your life depended on it. And it does.",
  "Yahtzee hates you personally.",
  "You're what happens when geometry gives up.",
  "I should've bought a Magic 8 Ball instead.",
  "You make bad decisions look like good options.",
  "Even loaded dice wouldn't cheat FOR you.",
  "Your best roll is everyone else's worst.",
  "You're the reason I believe in curses.",
  "Statistically, you shouldn't be this bad. Yet here we are.",
  "You're less random, more deliberately terrible.",
  "My horoscope was more accurate than you.",
  "You're proof that some shapes shouldn't exist.",
  "I've seen better rolls from a dying hamster wheel.",
  "You make craps players look optimistic.",
  "Did you go to school for being useless or is it natural?",
  "You're the flat earther of dice - fundamentally wrong.",
  "Even pi is less irrational than your results.",
  "You should be ashamed of all six of your faces.",
  "I'd trade you for a coin flip and lose on purpose.",
  "You're the 'check engine light' of gaming.",
  "Somewhere, a casino is laughing at us both.",
  "Your only talent is crushing dreams.",
  "You're not unlucky. You're aggressively hostile.",
];

export const getRandomInsult = (): string => {
  const randomIndex = Math.floor(Math.random() * diceInsults.length);
  return diceInsults[randomIndex];
};
